#include "Scene/Node.h"

#include "Core/Reflection/ReflectionImplMacros.h"

IMPLEMENT_REFLECTION_POINTER(Node)

REFLECT_STRUCT_BASE_BEGIN(Node)
REFLECT_STRUCT_MEMBER(m_enabled)
REFLECT_STRUCT_MEMBER(m_name)
REFLECT_STRUCT_MEMBER(m_entities)
REFLECT_STRUCT_MEMBER(m_localTransform)
REFLECT_STRUCT_MEMBER(m_children)
REFLECT_STRUCT_MEMBER(m_parent)
REFLECT_STRUCT_END(Node)