#pragma once

#define MAX_DIRLIGHTS   5
#define MAX_SPOTLIGHTS  5
#define MAX_POINTLIGHTS 5

#define PCBUFF_DIRLIGHT_SLOT	0
#define PCBUFF_POINTLIGHT_SLOT	1
#define PCBUFF_SPOTLIGHT_SLOT	2
#define PCBUFF_FREE_SLOT		3

#define VCBUFF_CAMERATRANSFORM_SLOT		0
#define VCBUFF_MODEL_SLOT		1
#define VCBUFF_BONES_SLOT		2
#define VCBUFF_LIGHTTRANSFORM_SLOT	3
#define VCBUFF_FREE_SLOT		4

#define TEX2D_SHADOWMAP_SLOT	0
#define TEX2D_FREE_SLOT			TEX2D_SHADOWMAP_SLOT + MAX_DIRLIGHTS