#pragma once

#define PCBUFF_DIRLIGHT_SLOT	0
#define PCBUFF_POINTLIGHT_SLOT	1
#define PCBUFF_SPOTLIGHT_SLOT	2
#define PCBUFF_FREE_SLOT		3

#define VCBUFF_CAMERATRANSFORM_SLOT		0
#define VCBUFF_MODEL_SLOT		1
#define VCBUFF_BONES_SLOT		2
#define VCBUFF_LIGHTTRANSFORM_SLOT	3
#define VCBUFF_FREE_SLOT		4

#define TEX2D_SHADOWMAP_SLOT	5