#include "MathWrappers.h"

using namespace math;

REFLECT_STRUCT_BASE_BEGIN(Vector3)
REFLECT_STRUCT_MEMBER(x)
REFLECT_STRUCT_MEMBER(y)
REFLECT_STRUCT_MEMBER(z)
REFLECT_STRUCT_END(Vector3)

REFLECT_STRUCT_BASE_BEGIN(Quaternion)
REFLECT_STRUCT_MEMBER(x)
REFLECT_STRUCT_MEMBER(y)
REFLECT_STRUCT_MEMBER(z)
REFLECT_STRUCT_MEMBER(w)
REFLECT_STRUCT_END(Quaternion)

REFLECT_STRUCT_BASE_BEGIN(Matrix4)
REFLECT_STRUCT_END(Matrix4)