#include "Node.h"

REFLECT_STRUCT_BASE_BEGIN(Node)
REFLECT_STRUCT_MEMBER(m_entities)
REFLECT_STRUCT_MEMBER(m_localTransform)
REFLECT_STRUCT_MEMBER(m_children)
REFLECT_STRUCT_MEMBER(m_parent)
REFLECT_STRUCT_MEMBER(m_globalTransform)
REFLECT_STRUCT_END()